class_name RoomMesh
extends Node3D

const FLOOR_THICKNESS := 1.0
const WALL_HEIGHT := 10
const WALL_THICKNESS := 0.5
const WALL_HEIGHT_SHRINK := 0.2
const RAMP_XY_RATIO := 5.0 / 3.0
const MIN_RAMP_HEIGHT := 0.1

## Doorway cutout size for flat (non-ramp) exits. Tune to taste.
const DOOR_WIDTH := 4.0
const DOOR_HEIGHT := 6.0

@export var floor_mesh: MeshInstance3D
@export var floor_collision: CollisionShape3D

@export var ramp_mesh: MeshInstance3D
@export var ramp_collision: CollisionShape3D

## Optional material applied to every generated wall segment, since these
## meshes are built at runtime and have no material assigned in the editor.
@export var wall_material: Material

var _ramp_instances: Array[MeshInstance3D] = []
var _ramp_collision_instances: Array[CollisionShape3D] = []

# All StaticBody3D wall pieces generated by the current call to
# _set_wall_mesh, so they can be torn down and rebuilt on the next call.
var _wall_pieces: Array[StaticBody3D] = []


func _ready():
	visible = false


func set_room_mesh(room: Room):
	visible = true
	var floor_top_y: float = room.entrance.position.y

	_set_floor_mesh(room, floor_top_y)
	_set_ramp_mesh(room, floor_top_y)
	_set_wall_mesh(room, floor_top_y)


func _set_wall_mesh(room: Room, floor_top_y: float):
	_clear_wall_pieces()

	var directions: Array[Vector3i] = Doorway.cardinals.duplicate()
	
	for i in range(len(directions)):
		var direction = directions[i]

		if direction == room.entrance.direction:
			if not room.previous_room:
				build_wall(direction, room)
				continue
			var previous_floor_local_y: float = room.previous_room.global_position.y - room.global_position.y

			if previous_floor_local_y < 0.0:
				build_doorway(room.entrance.direction, room, room.entrance)
			else:
				var previous_floor: Doorway = Doorway.new(Vector3(0, previous_floor_local_y, 0), room.entrance.direction)
				build_connector(direction, room, previous_floor)
			continue

		var exit_id = room.exits.find_custom(func(e): return e.direction == direction)
		if exit_id == -1:
			build_wall(direction, room)
			continue

		var exit: Doorway = room.exits[exit_id]
		var height_diff: float = exit.position.y - floor_top_y

		if height_diff <= 0.0:
			build_doorway(direction, room, exit)
		else:
			build_connector(direction, room, exit)


func build_wall(direction: Vector3i, room: Room) -> void:
	var floor_top_y: float = room.entrance.position.y
	var place_dir: Vector3 = -(direction as Vector3)
 
	var box_size: Vector3
	if abs(place_dir.x) > 0.5:
		box_size = Vector3(WALL_THICKNESS, WALL_HEIGHT - WALL_HEIGHT_SHRINK, room.size.z)
	else:
		box_size = Vector3(room.size.x, WALL_HEIGHT - WALL_HEIGHT_SHRINK, WALL_THICKNESS)
 
	var position: Vector3 = place_dir * (room.size / 2)
	position.y = floor_top_y + WALL_HEIGHT / 2.0 - WALL_HEIGHT_SHRINK / 2.0
 
	create_box(position, box_size)


func build_connector(direction: Vector3i, room: Room, exit: Doorway) -> void:
	var floor_top_y: float = room.entrance.position.y
	var exit_y: float = exit.position.y
	var place_dir: Vector3 = -(direction as Vector3)

	var y_bottom: float = min(floor_top_y, exit_y)
	var y_top: float = max(floor_top_y, exit_y)
	var height: float = y_top - y_bottom
	if height < 0.01:
		return

	var box_size: Vector3
	if abs(place_dir.x) > 0.5:
		box_size = Vector3(WALL_THICKNESS, height - WALL_HEIGHT_SHRINK, room.size.z)
	else:
		box_size = Vector3(room.size.x, height - WALL_HEIGHT_SHRINK, WALL_THICKNESS)

	var position: Vector3 = place_dir * (room.size / 2)
	position.y = (y_bottom + y_top) / 2.0 - WALL_HEIGHT_SHRINK / 2.0

	create_box(position, box_size)
 
 
func build_doorway(direction: Vector3i, room: Room, exit: Doorway) -> void:
	var floor_top_y: float = room.entrance.position.y
	var place_dir: Vector3 = -(direction as Vector3)
	var ceiling_y: float = floor_top_y + WALL_HEIGHT
 
	var lateral_center: float = exit.position.z if abs(place_dir.x) > 0.5 else exit.position.x
 
	var full_width: float = room.size.z if abs(place_dir.x) > 0.5 else room.size.x
	var half_width: float = full_width / 2.0
	var door_half: float = DOOR_WIDTH / 2.0
 
	var segments: Array = []
 
	var left_edge: float = lateral_center - door_half
	var wall_left_edge: float = -half_width
	if left_edge - wall_left_edge > 0.01:
		segments.append({
			"lateral_center": (wall_left_edge + left_edge) / 2.0,
			"width": left_edge - wall_left_edge,
			"y_bottom": floor_top_y,
			"y_top": ceiling_y,
		})
 
	var right_edge: float = lateral_center + door_half
	var wall_right_edge: float = half_width
	if wall_right_edge - right_edge > 0.01:
		segments.append({
			"lateral_center": (right_edge + wall_right_edge) / 2.0,
			"width": wall_right_edge - right_edge,
			"y_bottom": floor_top_y,
			"y_top": ceiling_y,
		})
 
	var door_top: float = floor_top_y + DOOR_HEIGHT
	if ceiling_y - door_top > 0.01:
		segments.append({
			"lateral_center": lateral_center,
			"width": DOOR_WIDTH,
			"y_bottom": door_top,
			"y_top": ceiling_y,
		})
 
	for seg in segments:
		var height: float = seg.y_top - seg.y_bottom
 
		var box_size: Vector3
		if abs(place_dir.x) > 0.5:
			box_size = Vector3(WALL_THICKNESS, height - WALL_HEIGHT_SHRINK, seg.width)
		else:
			box_size = Vector3(seg.width, height - WALL_HEIGHT_SHRINK, WALL_THICKNESS)
 
		var position: Vector3 = place_dir * (room.size / 2)
		if abs(place_dir.x) > 0.5:
			position.z = seg.lateral_center
		else:
			position.x = seg.lateral_center
		position.y = (seg.y_bottom + seg.y_top) / 2.0 - WALL_HEIGHT_SHRINK / 2.0
 
		create_box(position, box_size)



func create_box(position: Vector3, size: Vector3) -> void:
	var body := StaticBody3D.new()
	if floor_collision and floor_collision.get_parent() is CollisionObject3D:
		var floor_body := floor_collision.get_parent() as CollisionObject3D
		body.collision_layer = floor_body.collision_layer
		body.collision_mask = floor_body.collision_mask
	add_child(body)
	body.position = position
	_wall_pieces.append(body)
 
	var mesh_instance := MeshInstance3D.new()
	var box_mesh := BoxMesh.new()
	box_mesh.size = size
	mesh_instance.mesh = box_mesh
 
	if wall_material is ShaderMaterial:
		var box_material: ShaderMaterial = wall_material.duplicate()
		var width: float = size.x if abs(size.x - WALL_THICKNESS) > 0.001 else size.z
		var height: float = size.y
		box_material.set_shader_parameter("uv_scale", Vector2(width, height/2))
		box_material.set_shader_parameter("uv_offset", Vector2.ZERO)
		mesh_instance.material_override = box_material
	elif wall_material:
		mesh_instance.material_override = wall_material
 
	body.add_child(mesh_instance)
 
	var collision_shape := CollisionShape3D.new()
	var box_shape := BoxShape3D.new()
	box_shape.size = size
	collision_shape.shape = box_shape
	body.add_child(collision_shape)
 
 
func _clear_wall_pieces() -> void:
	for piece in _wall_pieces:
		piece.queue_free()
	_wall_pieces.clear()



func _set_floor_mesh(room: Room, floor_top_y: float):
	var size = room.size
	size.y = FLOOR_THICKNESS
	(floor_mesh.mesh as BoxMesh).size = size
	(floor_collision.shape as BoxShape3D).size = size
	
	floor_mesh.position.y = floor_top_y - FLOOR_THICKNESS / 2.0


func _set_ramp_mesh(room: Room, floor_top_y: float):
	_clear_extra_ramps()

	var ramp_index: int = 0
	for exit in room.exits:
		if abs(exit.position.y - floor_top_y) < MIN_RAMP_HEIGHT:
			continue

		var mesh_node: MeshInstance3D
		var collision_node: CollisionShape3D

		if ramp_index == 0:
			mesh_node = ramp_mesh
			collision_node = ramp_collision
			mesh_node.visible = true
		else:
			mesh_node = ramp_mesh.duplicate()
			mesh_node.mesh = ramp_mesh.mesh.duplicate()
			add_child(mesh_node)
			_ramp_instances.append(mesh_node)

			var body_index: int = ramp_mesh.get_children().find(ramp_collision.get_parent())
			if body_index == -1:
				push_error("RoomMesh: ramp_collision's parent is not a child of ramp_mesh - check scene structure")
				continue
			var body_node: Node = mesh_node.get_child(body_index)

			var collision_index: int = ramp_collision.get_parent().get_children().find(ramp_collision)
			collision_node = body_node.get_child(collision_index)

		# Duplicated nodes copy whatever `disabled` state the template had at
		# duplication time, so make sure any ramp actually in use is enabled
		# regardless of what a previous rebuild left it as.
		collision_node.disabled = false

		_set_ramp(room, exit, floor_top_y, mesh_node, collision_node)
		ramp_index += 1

	if ramp_index == 0:
		# No exit needs a ramp - hide the mesh AND disable its collision, or
		# the invisible ramp keeps blocking the doorway.
		ramp_mesh.visible = false
		ramp_collision.disabled = true


func _clear_extra_ramps() -> void:
	for r in _ramp_instances:
		r.queue_free()
	_ramp_instances.clear()


func _set_ramp(room: Room, exit: Doorway, floor_top_y: float, mesh_node: MeshInstance3D, collision_node: CollisionShape3D) -> void:
	var exit_y: float = exit.position.y
	var is_down: bool = exit_y < floor_top_y

	var ramp_height: float = abs(exit_y - floor_top_y)
	var ramp_width: float = ramp_height * RAMP_XY_RATIO

	var to_interior: Vector3 = -Vector3(exit.direction.x, 0, exit.direction.z).normalized()

	var yaw: float = atan2(-to_interior.z, to_interior.x)
	if is_down:
		yaw += PI

	mesh_node.position = exit.position
	mesh_node.position.y = (floor_top_y + exit_y) / 2.0
	mesh_node.rotation = Vector3.ZERO
	mesh_node.rotation.y = yaw

	var ramp_mesh_prism: PrismMesh = mesh_node.mesh as PrismMesh
	ramp_mesh_prism.size.y = ramp_height
	ramp_mesh_prism.size.x = ramp_width

	var offset_sign: float = 1.0 if is_down else -1.0
	var local_shift: Vector3 = to_interior * (ramp_width / 2.0) * offset_sign
	mesh_node.position += local_shift

	var convex_shape: ConvexPolygonShape3D = ramp_mesh_prism.create_convex_shape()
	if convex_shape and convex_shape.points.size() >= 3:
		collision_node.shape = convex_shape
	else:
		var box := BoxShape3D.new()
		box.size = Vector3(ramp_width, ramp_height, ramp_mesh_prism.size.z)
		collision_node.shape = box
